apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-lister
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-lister-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployment-lister
subjects:
- kind: ServiceAccount
  name: istiod-basic
  namespace: istio-system
