apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster1
  namespace: kafka
spec:
  kafka:
    config:
      default.replication.factor: 1
      inter.broker.protocol.version: "3.3"
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - configuration:
        bootstrap:
          alternativeNames:
          - my-cluster1-kafka-bootstrap.kafka.${CLUSTER}
        brokers:
        - advertisedHost: my-cluster1-kafka-0.kafka.${CLUSTER}
          advertisedPort: 443
          broker: 0
      name: tls
      port: 9093
      tls: true
      type: cluster-ip
    replicas: 1
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 100Gi
        type: persistent-claim
    version: 3.3.2
  zookeeper:
    replicas: 1
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: my-cluster1-kafka-tls-bootstrap
  namespace: kafka
spec:
  hostnames:
  - my-cluster1-kafka-bootstrap.kafka.${CLUSTER}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: istio-ingress
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: my-cluster1-kafka-tls-bootstrap
      port: 9093
      weight: 1
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: my-cluster1-kafka-tls-0
  namespace: kafka
spec:
  hostnames:
  - my-cluster1-kafka-0.kafka.${CLUSTER}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: istio-ingress
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: my-cluster1-kafka-tls-0
      port: 9093
      weight: 1
